### ISSUE TITLE
iOS is unsupported?

### ISSUE THREAD

**Issue by privettoli** [goderbauer/contact_picker#23]
```log
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method selectContact on channel contact_picker)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      ContactPicker.selectContact (package:contact_picker/contact_picker.dart:23:24)
#2      AddFriendState.build.<anonymous closure> (package:socia_reto/add_friend.dart:30:56)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7<…>
```

**Comment by privettoli** [comment]
Never mind, seems like it was local misconfiguration.
